#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';
use D8Hack\HackCommand;
use Symfony\Component\Console\Application;
$application = new Application('D8Hack', '0.1-dev');
$application->add(new HackCommand());
$application->run();
